sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 8
  - 10
matrix:
  fast_finish: true
script: npm run travis
env:
  - BUCKET=http://pelias-data.nextzen.org.s3.amazonaws.com/placeholder
before_install:
  - npm i -g npm
before_script:
  - mkdir data
  - 'curl -sfo data/store.sqlite3.gz ${BUCKET}/archive/$(date +%Y-%m-%d)/store.sqlite3.gz || true'
  - '[ -e data/store.sqlite3.gz ] || curl -so data/store.sqlite3.gz ${BUCKET}/store.sqlite3.gz'
  - gunzip data/store.sqlite3.gz
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      node_js: 10
      script: curl "https://raw.githubusercontent.com/pelias/ci-tools/master/semantic-release.sh" | bash -
      if: branch = master
